1
SELECT REPLACE('MALAYALAM','A','E');

2
SELECT COALESCE(COMM, 0) FROM EMP;

3 
SELECT COUNT(*) FROM EMP WHERE JOB = 'CLERK';

4 
SELECT DEPTNO, COUNT(*) FROM EMP GROUP BY DEPTNO;

5 
SELECT COUNT(*) FROM EMP WHERE JOB = 'CLERK' AND HIREDATE > '1981-JAN-01';

6 
SELECT SUM(SAL + COALESCE(COMM, 0)) FROM EMP;

7 
SELECT ENAME,12 * (SAL + COALESCE(COMM, 0)) AS ANNUAL FROM EMP WHERE JOB = 'MANAGER';

8 
SELECT AVG(SAL) FROM EMP WHERE JOB = 'SALESMAN';

9 
SELECT ENAME, JOB FROM EMP WHERE SAL = ( SELECT MAX(SAL) FROM EMP );

10 
SELECT ENAME, JOB, DEPTNO FROM EMP E1 WHERE SAL = ( SELECT MAX(SAL) FROM EMP E2 WHERE E1.DEPTNO = E2.DEPTNO);

11 
SELECT MIN(ENAME) FROM EMP;

12 
SELECT JOB, MIN(SAL) FROM EMP GROUP BY JOB;

13 
SELECT DEPTNO, JOB, MAX(SAL) FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO, JOB;

14 
SELECT DEPTNO, JOB, MAX(SAL) FROM EMP GROUP BY DEPTNO, JOB HAVING MAX(SAL) > 1500;

15 
SELECT MIN(SAL), MAX(SAL), DEPTNO FROM EMP WHERE JOB = 'MANAGER' GROUP BY DEPTNO;

16 
SELECT DEPTNO, JOB, MIN(SAL) FROM EMP WHERE JOB = 'MANAGER' GROUP BY DEPTNO, JOB HAVING MIN(SAL) > 2500;