1
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM EMPLOYEE
  WHERE JOB = 'Manager';
  DBMS_OUTPUT.PUT_LINE('No. of Managers: ' || v_count);
END;

2
DECLARE
  v_emp EMPLOYEE%ROWTYPE;
BEGIN
  SELECT * INTO v_emp
  FROM EMPLOYEE
  WHERE EMPNO = 7369;
  DBMS_OUTPUT.PUT_LINE('Employee: ' || v_emp.ENAME || ', Salary: ' || v_emp.SALARY);
END;

3
DECLARE
  v_date DATE;
BEGIN
  SELECT ROUND(HIREDATE, 'MONTH') INTO v_date
  FROM EMPLOYEE
  WHERE EMPNO = 7369; 
  DBMS_OUTPUT.PUT_LINE('Rounded DOJ: ' || v_date);
END;

4
DECLARE
  v_emp EMPLOYEE%ROWTYPE;
BEGIN
  SELECT * INTO v_emp
  FROM EMPLOYEE
  WHERE SALARY = (
    SELECT MAX(SALARY) FROM EMPLOYEE WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE)
  );
  DBMS_OUTPUT.PUT_LINE('Second Highest Salary: ' || v_emp.ENAME || ', ' || v_emp.SALARY);
END;

5
DECLARE
  CURSOR c_emp IS SELECT * FROM EMPLOYEE WHERE DNO = 40;
  v_emp EMPLOYEE%ROWTYPE;
BEGIN
  FOR v_emp IN c_emp LOOP
    DBMS_OUTPUT.PUT_LINE('Employee: ' || v_emp.ENAME || ', Dept: ' || v_emp.DNO);
  END LOOP;
END;

6
DECLARE
  v_high EMPLOYEE.ENAME%TYPE;
  v_low EMPLOYEE.ENAME%TYPE;
BEGIN
  SELECT ENAME INTO v_high FROM EMPLOYEE
  WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE);
  SELECT ENAME INTO v_low FROM EMPLOYEE
  WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEE);
  DBMS_OUTPUT.PUT_LINE('Highest: ' || v_high);
  DBMS_OUTPUT.PUT_LINE('Lowest: ' || v_low);
END;

7
DECLARE
  v_name EMPLOYEE.ENAME%TYPE;
BEGIN
  SELECT ENAME INTO v_name
  FROM EMPLOYEE
  WHERE COMM = (SELECT MAX(COMM) FROM EMPLOYEE);
  DBMS_OUTPUT.PUT_LINE('Highest Commission: ' || v_name);
END;

8
DECLARE
  CURSOR c_emp IS
    SELECT ENAME 
    FROM EMPLOYEE 
    WHERE ENAME LIKE '_M%';
BEGIN
  FOR r IN c_emp LOOP
    DBMS_OUTPUT.PUT_LINE('Employee: ' || r.ENAME);
  END LOOP;
END;

9
DECLARE
  v_name EMPLOYEE.ENAME%TYPE;
BEGIN
  SELECT ENAME INTO v_name
  FROM EMPLOYEE
  WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMPLOYEE);
  DBMS_OUTPUT.PUT_LINE('Earliest Joined: ' || v_name);
END;

10
DECLARE
  v_sal NUMBER(10,2);
BEGIN
  SELECT ROUND(SALARY, 2) INTO v_sal
  FROM EMPLOYEE
  WHERE EMPNO = 7369;  
  DBMS_OUTPUT.PUT_LINE('Salary (2 decimals): ' || v_sal);
END;








