1
CREATE OR REPLACE VIEW A6V1 AS
SELECT ENAME, ADDRESS, BDATE, SEX
FROM EMPLOYEE;

2
CREATE OR REPLACE VIEW A6V2 AS
SELECT ENAME, ESRNO, SALARY, MGRSRNO, DNO
FROM EMPLOYEE
ORDER BY ENAME;

3
CREATE OR REPLACE VIEW A6V3 AS
SELECT ENAME AS NAME, BDATE AS DOB, ESRNO, SALARY, MGRSRNO, DNO
FROM EMPLOYEE
WHERE DNO IN (1, 3);

4
CREATE OR REPLACE VIEW A6V4 AS
SELECT ESRNO AS EID, DNO, SALARY AS SAL, (SALARY * 0.45) AS COMM
FROM EMPLOYEE;

5
CREATE OR REPLACE VIEW A6V5 AS
SELECT INITCAP(ENAME) AS ENAME, EXTRACT(YEAR FROM BDATE) AS YOB, SEX AS GENDER, ADDRESS AS ADDR
FROM EMPLOYEE;

6
CREATE OR REPLACE VIEW A6V6 AS
SELECT DNUMBER AS DNUM, UPPER(DLOCATION) AS DLOC
FROM DEPT_LOCATION;

7
CREATE OR REPLACE VIEW A6V7 AS
SELECT E.ENAME, E.ESRNO, E.MGRSRNO, E.SALARY, D.DNUMBER, D.DNAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DNO = D.DNUMBER;

8
CREATE OR REPLACE VIEW A6V8 AS
SELECT E.ENAME, E.ESRNO, E.BDATE, E.DNO, DL.DLOCATION
FROM EMPLOYEE E
JOIN DEPT_LOCATION DL ON E.DNO = DL.DNUMBER;

9
CREATE OR REPLACE VIEW A6V9 AS
SELECT ESRNO, SUM(HOURS) AS TIME
FROM WORKS_ON
GROUP BY ESRNO;

10
CREATE OR REPLACE VIEW A6V10 AS
SELECT E.ESRNO, E.ENAME, D.DNUMBER AS DNO, D.DNAME, DL.DLOCATION, P.PNUMBER, P.PNAME, P.PLOCATION
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DNO = D.DNUMBER
JOIN DEPT_LOCATION DL ON D.DNUMBER = DL.DNUMBER
JOIN PROJECT P ON D.DNUMBER = P.DNUM;

11
CREATE OR REPLACE VIEW A6V11 AS
SELECT E.ENAME, E.ESRNO, E.SALARY AS ESAL, E.MGRSRNO, M.ENAME AS MGRNAME, M.SALARY AS MSAL
FROM EMPLOYEE E
JOIN EMPLOYEE M ON E.MGRSRNO = M.ESRNO;

12
INSERT INTO DEPT_LOCATION (DNUMBER, DLOCATION)
VALUES (5, 'MANCHESWAR');
